# our source proxy
# source "https://gems-read#{ENV['NEXUS_PASS']}:@nexus.twistbioscience-staging.com/repository/all-ruby/"
source 'http://rubygems.org'

ruby '2.6.3'

# linter
gem 'rubocop'

# Adds a mixin that allows definition of abstract classes.
gem 'abstraction', '~>0.0.4'

group :test do
  gem 'minitest'
  gem 'minitest-mock_expectations', require: false
  gem 'minitest-reporters'
  gem 'minitest-stub_on_roids', require: false
  gem 'minitest-test_profile'
end

# JSON parsing
gem 'hjjeon-nextson', '~>1.2.1'

# Vault integration for fetching secrets
gem 'vault', '~> 0.10.1'

# doc
gem 'yard'
